//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingletonDemo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SingletonDbEntities : DbContext
    {
        public static SingletonDbEntities dbObj;
        public static int counter = 0;
        private static readonly object _lock = new object();
        private SingletonDbEntities()
            : base("name=SingletonDbEntities")
        {
            counter++;
        }
        public static SingletonDbEntities GetInstance
        {
            get
            {
                if (dbObj == null)
                {
                    lock (_lock)
                    {
                        if (dbObj == null)
                            dbObj = new SingletonDbEntities();
                    }
                }
                return dbObj;
            }
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Employee> Employees { get; set; }
    }
}
